### ISSUE TITLE
Bug: schema not updated.

### ISSUE THREAD

**Issue by sbuisson** [json-schema-faker/json-schema-faker#552] opened 2020-01-14 10:44 UTC
hello,
suddently (i think it worked yesterday)
when i click on generate example, it don't take my current shema, but a previous version. If i use an example, it will work, but if i modify the schema, it will stay the original schema who will generate data

**Comment by sbuisson** [comment] 2020-01-14 10:47
It suddently fix. I don't know what happen

**Comment by pateketrueke** [comment] 2020-01-14 15:49
Oh I see, so the webap is buggy!

Closing as duplicate of #553

**Closed by pateketrueke** 2020-01-14 15:49 UTC
