### ISSUE TITLE
Optional maxItems, minItems and maxLength  doesn't work

### ISSUE THREAD

**Issue by atomsfat** [json-schema-faker/json-schema-faker#456] opened 2018-08-28 00:05 UTC
# 0.5.0-rc15
## maxItems, minItems
* Using this schema https://json-schema-faker.js.org/#gist/f4ad1818735f0d0babdc1f12b92013f1
* Setting maxItems to 1 a minItems to 1 on website-jsf  on the options setting
* Expect that array must have just one item
* Also I made a test on nodejs same thing.

## maxLength

* Setting maxLength to 20 and minLength to 20 on website-jsf and using the schema below
* Expect that strings must be length 20
----
* There is not documentation about minItems or minLength

```json
{
  "type": "object",
  "properties": {
    "user": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/definitions/positiveInt"
        },
        "name": {
          "type": "string",
          "minLength" : 1,
          "maxLength" : 1,
          "faker": "name.findName"
        },
        "birthday": {
          "type": "string",
          "chance": {
            "birthday": {
              "string": true
            }
          }
        },
        "email": {
          "type": "string",
          "format": "email",
          "faker": "internet.email"
        }
      },
      "required": [
        "id",
        "name",
        "birthday",
        "email"
      ]
    }
  },
  "required": [
    "user"
  ],
  "definitions": {
    "positiveInt": {
      "type": "integer",
      "minimum": 0,
      "minimumExclusive": true
    }
  }
}
```

**Comment by mralexho** [comment] 2018-08-29 15:32
Stuck on this one as well. What would I need to do to add multiple **users**?

```
export const schema = {
  type: 'object',
  properties: {
    users: {
      type: 'object',
      properties: {
        id: {
          type: 'integer',
          minimum: 0,
          exclusiveMinimum: true
        },
        firstName: {
          type: 'string',
          faker: 'name.firstName'
        },
        lastName: {
          type: 'string',
          faker: 'name.lastName'
        },
        email: {
          type: 'string',
          format: 'email',
          faker: 'internet.email'
        }
      },
      required: ['id', 'firstName', 'lastName', 'email']
    },
  },
  required: ['users'],
};
```

**Comment by mralexho** [comment] 2018-08-29 15:47
Figured it out. Changed **users** to the `array` type like so:

```
export const schema = {
  type: 'object',
  properties: {
    users: {
      type: 'array',
      items: {
        id: {
          type: 'integer',
          minimum: 0,
          exclusiveMinimum: true
        },
        firstName: {
          type: 'string',
          faker: 'name.firstName'
        },
        lastName: {
          type: 'string',
          faker: 'name.lastName'
        },
        email: {
          type: 'string',
          format: 'email',
          faker: 'internet.email'
        }
      },
      minItems: 3,
      maxItems: 5,
      required: ['id', 'firstName', 'lastName', 'email']
    },
  },
  required: ['users'],
};
```

**Comment by pateketrueke** [comment] 2018-08-29 18:30
@atomsfat 

> maxItems, minItems

Gotcha, the defaults are not working.

> maxLength

It is actually working fine in the given schema: 

```json
{
  "type": "string",
  "minLength": 20,
  "maxLength": 20,
  "faker": "name.findName"
}
```

Of course I think defaults are broken too, we're missing docs.

**Comment by adrien-gueret** [comment] 2018-09-13 15:36
Hi @pateketrueke! 

I'm not sure to understand where this issue is going: is it planned to fix it?

As for now, setting `maxItems` property to an array will always generate an array with fixed number of items, depending of `optionalsProbability` property.

It seems to be because of this line: https://github.com/json-schema-faker/json-schema-faker/blob/master/lib/index.js#L808

```js
var length = (maxItems != null && optionalsProbability)
        ? Math.round(maxItems * optionalsProbability)
        : random.number(minItems, maxItems, 1, 5), 
```

`Math.round(maxItems * optionalsProbability)` will always return the same number of items here.
I assume there is a reason, but why not simply using `var length =  random.number(minItems, maxItems);`?

Well, I can make a PR if you want :)

Cheers!

**Comment by pateketrueke** [comment] 2018-09-14 19:08
> is it planned to fix it?

Yes.

The purpose behind `optionalsProbability` is to generate the amount of items given a percentage, e.g. `0.5` will give you half properties or items available filled.

The `maxItems` option will coerce any given value for this schema, so even if you use `"maxItems": 100` in your schema and you set `maxItems: 10` you'll get only up to 10 items instead.

Seems like we're taking into account the `maxItems` given as option, just that.

> Well, I can make a PR if you want :)

Please use the `develop` branch for your work.

**Comment by pateketrueke** [comment] 2018-09-16 17:57
After further investigation I realized the bug for `minItems/maxItems` happens only on the website, not on the library so that's not a bug here.

Also `maxLength` is working great, it will truncate your `maxLength` only if it is greater than the default, otherwise it remains the same.

I'm closing this since I guess is not longer an issue, thank you everyone.

**Closed by pateketrueke** 2018-09-16 17:57 UTC
Labels: discussion, docs improvement, working in progress

**Comment by adrien-gueret** [comment] 2018-09-17 08:39
Hi @pateketrueke 

I'm sorry to persist, but I don't understand how the bug cannot be on the library: 

```js
 const length = (maxItems != null && optionalsProbability)
    ? Math.round(maxItems * optionalsProbability)
    : random.number(minItems, maxItems, 1, 5);
```

This piece of code clearly tells that if we define `maxItems` and `optionalsProbability`, length of the generated array will be always the same.  
In my opinion, `optionalsProbability` should only set the probability to generate the array itself, but it should not affect its items.

As an user, when I define an array with `minItem` to X and `maxItems` to Y, I expect to get an array randomly fill with N items, where N is between X and Y, no matter the value of `optionalsProbability`.

To be clear, if I define an optional array with `minItem` to 1 and `maxItem` to 4, while having `optionalsProbability` to 0.5, I expect this:

- 50% of chance to not have any array
- 50% of chance to have an array with 1, 2, 3 or 4 items

As for today, I will have that:

- 50% of chance to not have any array
- 50% of chance to have an array with 2 items

It really feels it's a bug.

Hope it's clear :)

**Comment by pateketrueke** [comment] 2018-09-17 15:21
You're right @adrien-gueret so let me explain what happened:

The main purpose of `optionalsProbability` was not about chances, it was about filling holes.

If you have an array with `minItems: 2`, `maxItems: 5` and `optionalsProbability: 0.5` you'll get from 2 to 3 items, becasue 50% of 5 (maxItems) is 2.5 but gets round to 3.

> The same occurs with object's properties, this is particularly useful when testing.

In fact, if you set `optionalsProbability: 1` you'll get from 2 to 5 items.

There was an issue here, because the generated value was the same over and over, and that was causing undesired results. That's why I added `fixedProbabilities` which enable/disable this behavior.

So, having `optionalsProbability: 1` and `fixedProbabilities: true` you'll always get the 5 items.

This is already implemented on `develop`, if you want to play with it:

```js
import jsf from './src';

const schema = {
  type: 'array',
  items: {
    type: 'string',
  },
  maxItems: 5,
  minItems: 2,
};

jsf.option({
  optionalsProbability: 1,
});

console.log(jsf.generate(schema));
```

**Comment by atomsfat** [comment] 2018-09-18 17:36
Nice, I just wonder which are the defaults?

**Comment by pateketrueke** [comment] 2018-09-18 17:39
> Nice, I just wonder which are the defaults?

You can get those with `jsf.option.getDefaults()` which returns: https://github.com/json-schema-faker/json-schema-faker/blob/develop/src/class/OptionRegistry.js#L5-L29
