### ISSUE TITLE
allOf doesn't work properly

### ISSUE THREAD

**Issue by mikaa123** [json-schema-faker/json-schema-faker#57] opened 2015-08-03 09:45 UTC
Hey there,
First, thanks a lot for this super useful lib. :)

I have a problem with `allOf`. When used, it seems to only include the last schema passed. Here is an example :

```javascript
var testSchema = {
  "definitions": {
    "address": {
      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city":           { "type": "string" },
        "state":          { "type": "string" }
      },
      "required": ["street_address", "city", "state"]
    }
  },

  "type": "object",

  "properties": {
    "billing_address": { "$ref": "#/definitions/address" },
    "shipping_address": {
      "allOf": [
        { "$ref": "#/definitions/address" },
        { "properties":
          { "type": { "enum": [ "residential", "business" ] } },
          "required": ["type"]
        }
      ]
    }
  }
};

jsf(testSchema);
```

The resulting JSON looks like this :
```json
{
  "shipping_address": {
    "type": "business"
  },
  "billing_address": {
    "street_address": "dolorum minima asperiores quas",
    "city": "quae ut explicabo",
    "state": "aspernatur ea est"
  }
}
```

(example taken from http://spacetelescope.github.io/understanding-json-schema/structuring.html)

I'm not sure the problem actually comes from json-schema-faker. Most likely from a dependency. I'll investigate further when I have some time.

**Comment by ducin** [comment] 2015-08-03 16:16
Hi @mikaa123, thanks for contacting us. Unfortunately, I confirm it is a problem with jsf, not your code.

In fact, jsf currently supports only trivial situations in `anyOf`, `allOf`, `oneOf`. It lies in the [json-schema-faker/lib/util/combine.js](https://github.com/pateketrueke/json-schema-faker/blob/master/lib/util/combine.js#L9) file. The existing code holds a container that would merge all attributes of all elements (elements of anyOf, allOf, anyOf). But it does a shallow merge, not a deep merge. In other words, if you've got following objects to be shallow-merged:
```json
{
  "type":"object",
  "properties":{
    "street_address":{
      "type":"string"
    },
    "city":{
      "type":"string"
    },
    "state":{
      "type":"string"
    }
  },
  "required":[
    "street_address",
    "city",
    "state"
  ]
}
```
and
```json
{
  "properties":{
    "type":{
      "enum":[
        "residential",
        "business"
      ]
    }
  },
  "required":[
    "type"
  ]
}
```

then both `properties` and `required` fields will get overriden by the last value (`target[key] = obj[key];` <- this line is evil), i.e.
```js
var target = {}; // in the beginning, target is empty
target.properties = firstElement.properties; // empty target merges with properties attribute of firstElement
target.properties = secondElement.properties; // target "merges" with properties attribute of secondElement, which is not merging, but overwriting
```

----

AFAIK, we need one of those:
* https://www.npmjs.com/package/underscore-deep-extend
* https://gist.github.com/kurtmilam/1868955
No sense to implement object deep merging on our own.

**Comment by ducin** [comment] 2015-08-03 16:17
When we do this issue, it'd be nice if all combiners (`allOf`, `oneOf`, `anyOf`) got fixed.

**Comment by pateketrueke** [comment] 2015-08-03 17:00
@ducin I prefer [deepmerge](https://github.com/KyleAMathews/deepmerge) to stay small.

**Comment by pateketrueke** [comment] 2015-08-03 17:02
> When we do this issue, it'd be nice if all combiners (allOf, oneOf, anyOf) got fixed.

Yes, many of those issues may be solved by fixing `deref` first.

I'll work on that asap, due many issues are related by dereferencing stuff.

**Comment by ducin** [comment] 2015-08-03 19:15
@pateketrueke so the issue is not where I pointed out?

PS I've tried to read through the core source code to make a bugfix, but I found it complex... Do you think it's possible that you could write few sentences of description on how everything works internally? I mean - what is the responsibility of deref (the input, the output), which parts are responsible for what? The only way to solve this is executing a step-by-step debugger, but it consumes huge amounts of time. And a small description could be helpful :) it's not a must, anyway, it'd be easier for me to join you in core stuff.

**Comment by pateketrueke** [comment] 2015-08-03 19:44
@ducin I'm not tried what you said about doing a deep merge, could you test that please?

However:

Fixing `deref` MUST help to mitigate these kind of issues but certainly not `jsf`'s ones, `jsf` MUST use `deref` only for dereference requested sub-schemas.

The current behavior is that `jsf` perform a full dereferencing before iterate anything, that is the key for everything: it must perform a lazy/progressive dereferencing while faking the schema  (fix #54 #44 - next major-release?).

A complex-but-common case of use is the main JSON-Schema _schema_ which is self-referenced recursively: http://json-schema.org/schema

So `jsf` MUST take care of that behavior, it can produce nested self-referenced objects 0-N times if its possible.

From the `jsf` side we can merge `allOf` sub-schemas first, and then dereference them.

Today we can try to patch `jsf`'s behavior and see what happens.

**Comment by ducin** [comment] 2015-08-10 21:29
I made a try and, unfortunately, deepmerge either doesn't seem to do the job or it will need some pimp-up before used, since it throws "cannot call ... on undefined" errors. Anyway, I tried to use underscore + underscore-deep-extend and my solution works for above case.

**Comment by Scorpil** [comment] 2015-09-08 08:59
I've stumbled upon this issue too. Thanks for looking into it, @ducin .
Do you think it would be a good idea to share your work through separate branch or PR so that we could review and maybe help with some issues?

**Comment by ducin** [comment] 2015-09-12 10:52
Hi @Scorpil, there is the ["guidelines for contributing"](https://github.com/json-schema-faker/json-schema-faker/blob/master/CONTRIBUTING.md), please take alook at it. Of course, the best way is to create your own branch and PR it against `develop`. Then we will look into it. Contribution is very welcome :)

**Comment by Scorpil** [comment] 2015-09-16 08:43
@ducin i know how github works, i've meant *your* branch. Nevermind, I'll just wait until fix is in master ;)

**Comment by ducin** [comment] 2015-09-16 08:45
This might take some time.... Again, you contribution would very welcome :) please keep in mind that there has been changes in the latest `0.2.1` version.

**Comment by pateketrueke** [comment] 2015-09-18 07:29
Seems to be solved in `develop` branch.

**Closed by pateketrueke** 2015-09-18 07:29 UTC
Labels: bug
